export const RegisterData = {
    countryCodes: [
        { value: '+93', name: 'Afghanistan', code: 'AF' },
        { value: '+355', name: 'Albania', code: 'AL' },
        { value: '+213', name: 'Algeria', code: 'DZ' },
        { value: '+1', name: 'American Samoa', code: 'AS' },
        { value: '+376', name: 'Andorra', code: 'AD' },
        { value: '+244', name: 'Angola', code: 'AO' },
        { value: '+1', name: 'Anguilla', code: 'AI' },
        { value: '+1', name: 'Antigua', code: 'AG' },
        { value: '+54', name: 'Argentina', code: 'AR' },
        { value: '+374', name: 'Armenia', code: 'AM' },
        { value: '+297', name: 'Aruba', code: 'AW' },
        { value: '+61', name: 'Australia', code: 'AU' },
        { value: '+43', name: 'Austria', code: 'AI' },
        { value: '+994', name: 'Azerbaijan', code: 'AZ' },
        { value: '+973', name: 'Bahrain', code: 'BH' },
        { value: '+880', name: 'Bangladesh', code: 'BD' },
        { value: '+1', name: 'Barbados', code: 'BB' },
        { value: '+375', name: 'Belarus', code: 'BY' },
        { value: '+32', name: 'Belgium', code: 'BE' },
        { value: '+501', name: 'Belize', code: 'BZ' },
        { value: '+229', name: 'Benin', code: 'BJ' },
        { value: '+1', name: 'Bermuda', code: 'BM' },
        { value: '+975', name: 'Bhutan', code: 'BT' },
        { value: '+591', name: 'Bolivia', code: 'BO' },
        { value: '+387', name: 'Bosnia & Herzegovina', code: 'BA' },
        { value: '+267', name: 'Botswana', code: 'BW' },
        { value: '+55', name: 'Brazil', code: 'BR' },
        { value: '+246', name: 'British Indian Ocean', code: 'IO' },
        { value: '+1', name: 'British Virgin Islands', code: 'VG' },
        { value: '+673', name: 'Brunei', code: 'BN' },
        { value: '+359', name: 'Bulgaria', code: 'BG' },
        { value: '+226', name: 'Burkina Faso', code: 'BF' },
        { value: '+95', name: 'Burma Myanmar', code: 'MM' },
        { value: '+257', name: 'Burundi', code: 'BI' },
        { value: '+855', name: 'Cambodia', code: 'KH' },
        { value: '+237', name: 'Cameroon', code: 'CM' },
        { value: '+1', name: 'Canada', code: 'CA' },
        { value: '+238', name: 'Cape Verde', code: 'CV' },
        { value: '+1', name: 'Cayman Islands', code: 'KY' },
        { value: '+236', name: 'Central African Republic', code: 'CF' },
        { value: '+235', name: 'Chad', code: 'ID' },
        { value: '+56', name: 'Chile', code: 'CL' },
        { value: '+86', name: 'China', code: 'CN' },
        { value: '+57', name: 'Colombia', code: 'CO' },
        { value: '+269', name: 'Comoros', code: 'KM' },
        { value: '+682', name: 'Cook Islands', code: 'CK' },
        { value: '+506', name: 'Costa Rica', code: 'CR' },
        { value: '+225', name: 'Côte dIvoire', code: 'CI' },
        { value: '+385', name: 'Croatia', code: 'HR' },
        { value: '+53', name: 'Cuba', code: 'CU' },
        { value: '+357', name: 'Cyprus', code: 'CY' },
        { value: '+420', name: 'Czech Republic', code: 'CZ' },
        { value: '+243', name: 'Republic of Congo', code: 'CD' },
        { value: '+45', name: 'Denmark', code: 'DK' },
        { value: '+253', name: 'Djibouti', code: 'DJ' },
        { value: '+1', name: 'Dominica', code: 'DM' },
        { value: '+1', name: 'Dominican Republic', code: 'DO' },
        { value: '+593', name: 'Ecuador', code: 'EC' },
        { value: '+20', name: 'Egypt', code: 'EG' },
        { value: '+503', name: 'El Salvador', code: 'SV' },
        { value: '+240', name: 'Equatorial Guinea', code: 'GQ' },
        { value: '+291', name: 'Eritrea', code: 'ER' },
        { value: '+372', name: 'Estonia', code: 'EE' },
        { value: '+251', name: 'Ethiopia', code: 'ET' },
        { value: '+500', name: 'Falkland Islands', code: 'FK' },
        { value: '+298', name: 'Faroe Islands', code: 'FO' },
        { value: '+691', name: 'Federated Micronesia', code: 'FM' },
        { value: '+679', name: 'Fiji', code: 'FJ' },
        { value: '+358', name: 'Finland', code: 'FI' },
        { value: '+33', name: 'France', code: 'FR' },
        { value: '+594', name: 'French Guiana', code: 'GF' },
        { value: '+689', name: 'French Polynesia', code: 'PF' },
        { value: '+241', name: 'Gabon', code: 'GA' },
        { value: '+995', name: 'Georgia', code: 'GE' },
        { value: '+49', name: 'Germany', code: 'DE' },
        { value: '+233', name: 'Ghana', code: 'GH' },
        { value: '+350', name: 'Gibraltar', code: 'GI' },
        { value: '+30', name: 'Greece', code: 'GR' },
        { value: '+299', name: 'Greenland', code: 'GL' },
        { value: '+1', name: 'Grenada', code: 'GD' },
        { value: '+590', name: 'Guadeloupe', code: 'GP' },
        { value: '+1', name: 'Guam', code: 'GU' },
        { value: '+502', name: 'Guatemala', code: 'GT' },
        { value: '+224', name: 'Guinea', code: 'GN' },
        { value: '+245', name: 'Guinea-Bissau', code: 'GW' },
        { value: '+592', name: 'Guyana', code: 'GY' },
        { value: '+509', name: 'Haiti', code: 'HT' },
        { value: '+504', name: 'Honduras', code: 'HN' },
        { value: '+852', name: 'Hong Kong', code: 'HK' },
        { value: '+36', name: 'Hungary', code: 'HU' },
        { value: '+354', name: 'Iceland', code: 'IS' },
        { value: '+91', name: 'India', code: 'IN' },
        { value: '+62', name: 'Indonesia', code: 'ID' },
        { value: '+98', name: 'Iran', code: 'IR' },
        { value: '+964', name: 'Iraq', code: 'IQ' },
        { value: '+353', name: 'Ireland', code: 'IE' },
        { value: '+972', name: 'Israel', code: 'IL' },
        { value: '+39', name: 'Italy', code: 'IT' },
        { value: '+1', name: 'Jamaica', code: 'JM' },
        { value: '+81', name: 'Japan', code: 'JP' },
        { value: '+962', name: 'Jordan', code: 'JO' },
        { value: '+7', name: 'Kazakhstan', code: 'KZ' },
        { value: '+254', name: 'Kenya', code: 'KE' },
        { value: '+686', name: 'Kiribati', code: 'KI' },
        { value: '+383', name: 'Kosovo', code: 'XK' },
        { value: '+965', name: 'Kuwait', code: 'KW' },
        { value: '+996', name: 'Kyrgyzstan', code: 'KG' },
        { value: '+856', name: 'Laos', code: 'LA' },
        { value: '+371', name: 'Latvia', code: 'LV' },
        { value: '+961', name: 'Lebanon', code: 'LB' },
        { value: '+266', name: 'Lesotho', code: 'LS' },
        { value: '+231', name: 'Liberia', code: 'LR' },
        { value: '+218', name: 'Libya', code: 'LY' },
        { value: '+423', name: 'Liechtenstein', code: 'LI' },
        { value: '+370', name: 'Lithuania', code: 'LT' },
        { value: '+352', name: 'Luxembourg', code: 'LU' },
        { value: '+853', name: 'Macau', code: 'MO' },
        { value: '+389', name: 'Macedonia', code: 'MK' },
        { value: '+261', name: 'Madagascar', code: 'MG' },
        { value: '+265', name: 'Malawi', code: 'MW' },
        { value: '+60', name: 'Malaysia', code: 'MY' },
        { value: '+960', name: 'Maldives', code: 'MV' },
        { value: '+223', name: 'Mali', code: 'ML' },
        { value: '+356', name: 'Malta', code: 'MT' },
        { value: '+692', name: 'Marshall Islands', code: 'MH' },
        { value: '+596', name: 'Martinique', code: 'MQ' },
        { value: '+222', name: 'Mauritania', code: 'MR' },
        { value: '+230', name: 'Mauritius', code: 'MU' },
        { value: '+262', name: 'Mayotte', code: 'YT' },
        { value: '+52', name: 'Mexico', code: 'MX' },
        { value: '+373', name: 'Moldova', code: 'MD' },
        { value: '+377', name: 'Monaco', code: 'MC' },
        { value: '+976', name: 'Mongolia', code: 'MN' },
        { value: '+382', name: 'Montenegro', code: 'ME' },
        { value: '+1', name: 'Montserrat', code: 'MS' },
        { value: '+212', name: 'Morocco', code: 'MA' },
        { value: '+258', name: 'Mozambique', code: 'MZ' },
        { value: '+264', name: 'Namibia', code: 'NA' },
        { value: '+674', name: 'Nauru', code: 'NR' },
        { value: '+977', name: 'Nepal', code: 'NP' },
        { value: '+31', name: 'Netherlands', code: 'NL' },
        { value: '+599', name: 'Netherlands Antilles', code: 'AN' },
        { value: '+687', name: 'New Caledonia', code: 'NC' },
        { value: '+64', name: 'New Zealand', code: 'NZ' },
        { value: '+505', name: 'Nicaragua', code: 'NI' },
        { value: '+227', name: 'Niger', code: 'NE' },
        { value: '+234', name: 'Nigeria', code: 'NG' },
        { value: '+683', name: 'Niue', code: 'NU' },
        { value: '+672', name: 'Norfolk Island', code: 'NF' },
        { value: '+850', name: 'North Korea', code: 'KP' },
        { value: '+1', name: 'Northern Mariana Islands', code: 'MP' },
        { value: '+47', name: 'Norway', code: 'NO' },
        { value: '+968', name: 'Oman', code: 'OM' },
        { value: '+92', name: 'Pakistan', code: 'PK' },
        { value: '+680', name: 'Palau', code: 'PW' },
        { value: '+970', name: 'Palestine', code: 'PS' },
        { value: '+507', name: 'Panama', code: 'PA' },
        { value: '+675', name: 'Papua New Guinea', code: 'PG' },
        { value: '+595', name: 'Paraguay', code: 'PY' },
        { value: '+51', name: 'Peru', code: 'PE' },
        { value: '+63', name: 'Philippines', code: 'PH' },
        { value: '+48', name: 'Poland', code: 'PL' },
        { value: '+351', name: 'Portugal', code: 'PT' },
        { value: '+1', name: 'Puerto Rico', code: 'PR' },
        { value: '+974', name: 'Qatar', code: 'QA' },
        { value: '+242', name: 'Republic of the Congo', code: 'CG' },
        { value: '+262', name: 'Réunion', code: 'RE' },
        { value: '+40', name: 'Romania', code: 'RO' },
        { value: '+7', name: 'Russia', code: 'RU' },
        { value: '+250', name: 'Rwanda', code: 'RW' },
        { value: '+590', name: 'Saint Barthélemy', code: 'BL' },
        { value: '+290', name: 'Saint Helena', code: 'SH' },
        { value: '+1', name: 'Saint Kitts and Nevis', code: 'KN' },
        { value: '+590', name: 'Saint Martin', code: 'MF' },
        { value: '+508', name: 'St Pierre & Miquelon', code: 'PM' },
        { value: '+1', name: 'St Vincent & Grenadines', code: 'VC' },
        { value: '+685', name: 'Samoa', code: 'WS' },
        { value: '+378', name: 'San Marino', code: 'SM' },
        { value: '+239', name: 'São Tomé and Príncipe', code: 'ST' },
        { value: '+966', name: 'Saudi Arabia', code: 'SA' },
        { value: '+221', name: 'Senegal', code: 'SN' },
        { value: '+381', name: 'Serbia', code: 'RS' },
        { value: '+248', name: 'Seychelles', code: 'SC' },
        { value: '+232', name: 'Sierra Leone', code: 'SL' },
        { value: '+65', name: 'Singapore', code: 'SG' },
        { value: '+421', name: 'Slovakia', code: 'SK' },
        { value: '+386', name: 'Slovenia', code: 'SI' },
        { value: '+677', name: 'Solomon Islands', code: 'SB' },
        { value: '+252', name: 'Somalia', code: 'SO' },
        { value: '+27', name: 'South Africa', code: 'ZA' },
        { value: '+82', name: 'South Korea', code: 'KR' },
        { value: '+34', name: 'Spain', code: 'ES' },
        { value: '+94', name: 'Sri Lanka', code: 'LK' },
        { value: '+1', name: 'St. Lucia', code: 'LC' },
        { value: '+249', name: 'Sudan', code: 'SD' },
        { value: '+597', name: 'Suriname', code: 'SR' },
        { value: '+268', name: 'Swaziland', code: 'SZ' },
        { value: '+46', name: 'Sweden', code: 'SE' },
        { value: '+41', name: 'Switzerland', code: 'CH' },
        { value: '+963', name: 'Syria', code: 'SY' },
        { value: '+886', name: 'Taiwan', code: 'TW' },
        { value: '+992', name: 'Tajikistan', code: 'TJ' },
        { value: '+255', name: 'Tanzania', code: 'TZ' },
        { value: '+66', name: 'Thailand', code: 'TH' },
        { value: '+1', name: 'The Bahamas', code: 'BS' },
        { value: '+220', name: 'The Gambia', code: 'GB'},
        { value: '+220', name: 'The Gambia', code: 'GM' },
        { value: '+670', name: 'Timor-Leste', code: 'TL' },
        { value: '+228', name: 'Togo', code: 'TG' },
        { value: '+690', name: 'Tokelau', code: 'TK' },
        { value: '+676', name: 'Tonga', code: 'TO' },
        { value: '+1', name: 'Trinidad and Tobago', code: 'TT' },
        { value: '+216', name: 'Tunisia', code: 'TN' },
        { value: '+90', name: 'Turkey', code: 'TR' },
        { value: '+993', name: 'Turkmenistan', code: 'TM' },
        { value: '+1', name: 'Turks and Caicos Islands', code: 'TC' },
        { value: '+688', name: 'Tuvalu', code: 'TV' },
        { value: '+256', name: 'Uganda', code: 'UG' },
        { value: '+380', name: 'Ukraine', code: 'UA' },
        { value: '+971', name: 'United Arab Emirates', code: 'AE' },
        { value: '+44', name: 'United Kingdom', code: 'GB' },
        { value: '+1', name: 'United States', code: 'US' },
        { value: '+598', name: 'Uruguay', code: 'UY' },
        { value: '+1', name: 'US Virgin Islands', code: 'VI' },
        { value: '+998', name: 'Uzbekistan', code: 'UZ' },
        { value: '+678', name: 'Vanuatu', code: 'VU' },
        { value: '+39', name: 'Vatican City', code: 'VA' },
        { value: '+58', name: 'Venezuela', code: 'VE' },
        { value: '+84', name: 'Vietnam', code: 'VN' },
        { value: '+681', name: 'Wallis and Futuna', code: 'WF' },
        { value: '+967', name: 'Yemen', code: 'YE' },
        { value: '+260', name: 'Zambia', code: 'ZM' },
        { value: '+263', name: 'Zimbabwe', code: 'ZW' }
    ]
};
